//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Inutil.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class epiEntities1 : DbContext
    {
        public epiEntities1()
            : base("name=epiEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<comentario> comentarios { get; set; }
        public virtual DbSet<etiqueta> etiquetas { get; set; }
        public virtual DbSet<etiquetas_noticias> etiquetas_noticias { get; set; }
        public virtual DbSet<noticia> noticias { get; set; }
        public virtual DbSet<sugerencia> sugerencias { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
    }
}
