//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Inutil.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class noticia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public noticia()
        {
            this.comentarios = new HashSet<comentario>();
            this.etiquetas_noticias = new HashSet<etiquetas_noticias>();
        }
    
        public long id { get; set; }
        public System.DateTime fecha { get; set; }
        public string titulo { get; set; }
        public string contenido { get; set; }
        public long usuario_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comentario> comentarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<etiquetas_noticias> etiquetas_noticias { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
