//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Inutil.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sugerencia
    {
        public long id { get; set; }
        public Nullable<long> tipo { get; set; }
        public long usuario_id { get; set; }
        public System.DateTime fecha { get; set; }
        public string contenido { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
